spring.datasource.url=jdbc:postgresql://db:5432/${POSTGRES_DB:inventory}
spring.datasource.username=${POSTGRES_USER:inventory}
spring.datasource.password=${POSTGRES_PASSWORD:inventory}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.h2.console.enabled=false

