spring.application.name=inventory-app
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/inventory;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

inventory.default-low-stock-threshold=5
spring.flyway.baseline-on-migrate=true
auth.password=${AUTH_PASSWORD}
